Create caiman_mc_save.py
vathes/canonical-imaging pull request #7
Opened 2020-11-07 06:13 UTC by kabilar

2020-11-09 04:43 UTC, ttngu207 requested changes
Can you package this into a function, part of the `img_loader.caiman` module.
so users can invoke with something like this:

```
...
from img_loader.caimain import save_mc

mc_fp = 'data_dir/motion_correction.hdf5'
save_mc(mc,  mc_fp)
```

2020-11-09 19:25 UTC, kabilar commented
Good idea.  Will update this pull request.  Thanks.

2020-11-09 22:23 UTC, ttngu207 commented on caiman_mc_save.py
> +
`Cn` can be computed here:

```
Cn = cm.local_correlations(mc_image .transpose(1,2,0))
Cn[np.isnan(Cn)] = 0
```

2020-11-17 18:36 UTC, ttngu207 requested changes

2020-11-17 18:36 UTC, ttngu207 commented on img_loaders/caiman_loader.py
> +    def extract_mc(self, caiman_fp):
no need to pass in `caiman_fp` here, instead you should make use of `caiman_fp` at the `__init__` step, so users don't have to pass in `caiman_fp` twice

2020-11-17 18:36 UTC, ttngu207 commented on img_loaders/caiman_loader.py
> +        self.skip_refinement       = self.h5f['skip_refinement']
I'd suggest to not returning these properties into `self` if there is not a need for them. The method is `extract_mc` so we can just return the `motion_correction` part.

2020-11-17 18:36 UTC, ttngu207 commented on img_loaders/caiman_loader.py
> +        self.h5f = h5py.File(caiman_fp, 'r')
`self.h5f` already exists (from `__init__`) so no need to recreate it here again

2020-11-18 16:09 UTC, ttngu207 commented on djimaging/processing.py
> +                caiman_loader_inst = caiman_loader.CaImAn(caiman_fp)
I'd suggest passing in the `data_dir` in instantiating the caiman loader, and move the logic of searching + verifying the `hdf5` file into the loader itself

2020-11-19 22:48 UTC, ttngu207 approved these changes

2020-11-19 22:48 UTC, ttngu207 commented on djimaging/processing.py
> +                output_files=[caiman_loader_inst.caiman_fp]
`caiman_loader_inst.caiman_fp` would return the absolute path of the caiman file, what we want is its relative path with respect to the user-specified `root_data_dir`, hence the extra step of doing `.relative_to(root)....` in line 155 that is commented out

2020-11-19 22:48 UTC, ttngu207 commented on img_loaders/caiman_loader.py
> +        return self
no real need to have to return `self` here, as there's already a handle on the instantiated object `CaImAn` already.
Something like:
```
cm_loader = CaImAn(path)
cm_loader.extract_mc()

cm_loader.motion_correction ...
```

2020-11-19 22:57 UTC, merged